# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3c3def1aec8bc284b099d521d11fc98bc4f856dfa5e8acab44e1209f59eea2fe3d135a819e90465f346b2ce9e983567c49128c32e696ccf700bbabcf55823c86

test:
  secret_key_base: 333bdb50419efc7b2fe36d36197e08dd79bf5ce644e6b4117727b6bb29db0aad7abad14ea2af6f417ad2af91cb90deb4592a0e6c73805cda50d7991f1dd7c815

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
